on:
  workflow_dispatch:

jobs:
  publish:
    name: Compile and publish OpusLib fork to Maven Central using gradle task
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
          packages: 'build-tools;22.0.1 platforms;android-22'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r10e

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: launch library publish task
        env:
          SIMLA_MOBILE_APPS_EMAIL: ${{ secrets.SIMLA_MOBILE_APPS_EMAIL }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew :opuslib:uploadArchives --stacktrace
